#!/usr/bin/env python3
"""Regenerate assets/css/syntax.css from Chroma's built-in styles.

Chroma emits one rule per line, prefixed by a comment:

    /* Keyword */ .chroma .k { color:#ff7b72 }

We scope each rule under a [data-theme] selector so both palettes can live in
one stylesheet, and drop Chroma's own background colours so code blocks inherit
--code-bg from main.css instead.

Usage: python3 scripts/gen_syntax_css.py [--hugo path/to/hugo]
"""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys

LIGHT_STYLE = "github"
DARK_STYLE = "github-dark"
OUT = pathlib.Path("assets/css/syntax.css")

RULE = re.compile(r"^(?P<lead>\s*(?:/\*.*?\*/\s*)?)(?P<sel>[^{}]+?)\s*\{(?P<body>[^{}]*)\}\s*$")
BACKGROUND = re.compile(r"\s*background-color\s*:[^;]+;?", re.I)


def generate(hugo: str, style: str) -> str:
    result = subprocess.run(
        [hugo, "gen", "chromastyles", f"--style={style}"],
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout


def scope(css: str, prefix: str) -> str:
    out: list[str] = []
    for line in css.splitlines():
        if not line.strip() or line.strip().startswith("/*") and "{" not in line:
            continue
        match = RULE.match(line)
        if not match:
            continue
        selectors = [s.strip() for s in match["sel"].split(",") if s.strip()]
        body = match["body"].strip()
        # The wrapper's background is owned by main.css, not the Chroma palette.
        if any(s in (".bg", ".chroma") for s in selectors):
            body = BACKGROUND.sub("", body).strip().strip(";").strip()
            if not body:
                continue
        scoped = ", ".join(f"{prefix} {s}" for s in selectors)
        out.append(f"{scoped} {{ {body} }}")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--hugo", default="hugo", help="path to the hugo binary")
    args = parser.parse_args()

    try:
        light = scope(generate(args.hugo, LIGHT_STYLE), ':root[data-theme="light"]')
        dark = scope(generate(args.hugo, DARK_STYLE), ':root[data-theme="dark"]')
    except FileNotFoundError:
        print(f"error: hugo not found at {args.hugo!r}", file=sys.stderr)
        return 1
    except subprocess.CalledProcessError as exc:
        print(f"error: {exc.stderr.strip()}", file=sys.stderr)
        return 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "/* Generated by scripts/gen_syntax_css.py -- do not edit by hand.\n"
        f"   Light palette: {LIGHT_STYLE}. Dark palette: {DARK_STYLE}. */\n\n"
        f"/* ---------- light ---------- */\n{light}\n\n"
        f"/* ---------- dark ---------- */\n{dark}\n"
    )
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
